name: emm
version: '1.0-SNAPSHOT'
main: org.example.awa.emm.Emm
api-version: '1.20'
commands:
  HelloWorld:
    description: Hello World!
  about:
    description: 233
  wupin:
    description: qwq
  sendmessage:
    description: awa